import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from 'next-themes'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App Admin Dashboard',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{' '}
				<div className='min-h-screen flex flex-col'>
					<main className='flex-1'>
						{' '}
						<ThemeProvider
							attribute='class'
							defaultTheme='system'
							enableSystem
							storageKey='theme'
						>
							{children}
						</ThemeProvider>
					</main>
					<footer className='bg-gray-600 text-center p-2'>© 2025 Admin Dashboard</footer>
				</div>
			</body>
		</html>
	)
}
